;;;; Solution for Problem 100 in Project Euler
;;;; Paulo Mendes, 16-SEP-2017
(defmacro pell-sequence ((varx vary) (x1 y1 n) &body body)
  (let ((xsym (gensym)) (ysym (gensym)))
  `(block Nil
    (let ((,xsym ,x1) (,ysym ,y1))
    (do ((,varx ,xsym (+ (* ,xsym ,varx) (* ,n ,ysym ,vary)))
         (,vary ,ysym (+ (* ,xsym ,vary) (* ,ysym    ,varx))))
        ()
        (progn ,@body))))))

(pell-sequence (x y) (7 5 2)
   (and (> (/ (1+ x) 2) (expt 10 12))
        (= -1 (- (expt x 2) (* 2 (expt y 2)))
        (return (/ (1+ y) 2)))))

;;; No-frills solution based on the code generated by the macro above.
(do ((x 7 (+ (* 7 x) (* 10 y))) (y 5 (+ (* 7 y) (*  5 x))))
    ((and (> (/ (1+ x) 2) (expt 10 12)) (= -1 (- (expt x 2) (* 2 (expt y 2))))) (/ (1+ y) 2)))
    
    
    
